### PR TITLE
fixing css

### PR DESCRIPTION
**Pull request by danmihaila**
probably a typo

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
Hi @danmihaila. This is not a typo it's intentionally added. The word-break: break-all in WebKit breaks things wherever, so instead of that we are using non-standard one for WebKit  word-break: break-word.

**Comment by danmihaila** [comment]
I agree with you but that one is not working well. I am not sure if you can still access this: https://feature-data.humdata.org/ckan-admin/requests_data

**Comment by ZoranPandovski** [comment]
Ok, if this resolve your issue i will merge it and create tag.

**Comment by danmihaila** [comment]
ok, thank you

**Pull request merged**
